package com.toyquaise.kaptan.logic

/**
 * Every level, in order. Maps are drawn top row first, one character per grid point: '.' water,
 * '#' rock, 'S' start, 'L' harbor. The tests check that each one can be finished and that each
 * teaches what it says (an order that matters, a token that is needed...).
 */
object Levels {
    private fun v(x: Int, y: Int) = Vec(x, y)

    private var count = 0
    private fun level(
        chapter: Chapter,
        map: String,
        vararg cards: Vec,
        current: Vec = Vec.ZERO,
        tokens: Tokens = Tokens(),
    ) = Level.parse(++count, chapter, map, cards.toList(), current, tokens)

    val all: List<Level> = listOf(
        // ---------------------------------------------------------------- the canal: one line
        // 1. One card: tap it, look at the arrow, sail.
        level(
            Chapter.CANAL,
            """
            ...
            ...
            ...
            .L.
            ...
            ...
            ...
            .S.
            ...
            """,
            v(0, 4),
        ),
        // 2. Two cards tip to tail add up; one card is too many.
        level(
            Chapter.CANAL,
            """
            ...
            .L.
            ...
            ...
            ...
            ...
            ...
            .S.
            ...
            """,
            v(0, 2), v(0, 4), v(0, 3),
        ),
        // 3. A card pointing back takes away; play it first and the boat leaves the canal.
        level(
            Chapter.CANAL,
            """
            ...
            ...
            ...
            ...
            .L.
            ...
            ...
            .S.
            ...
            """,
            v(0, 5), v(0, -2), v(0, 4),
        ),
        // 4. × 2: a vector multiplied by a real number keeps its direction and grows.
        level(
            Chapter.CANAL,
            """
            ...
            .L.
            ...
            ...
            ...
            ...
            ...
            .S.
            ...
            """,
            v(0, 3), v(0, 2),
            tokens = Tokens(doubles = 1),
        ),
        // 5. × (−1): the opposite vector, same size, turned around.
        level(
            Chapter.CANAL,
            """
            ...
            .S.
            ...
            ...
            ...
            .L.
            ...
            ...
            ...
            """,
            v(0, 2), v(0, 6),
            tokens = Tokens(flips = 1),
        ),
        // 6. × ½ halves a card; a long way round works too, but takes two moves.
        level(
            Chapter.CANAL,
            """
            ...
            ...
            ...
            ...
            ...
            .L.
            ...
            .S.
            ...
            """,
            v(0, 6), v(0, 4),
            tokens = Tokens(halves = 1, flips = 1),
        ),

        // ---------------------------------------------------------------- the harbor: tip to tail
        // 7. Round the corner: 3 east and 4 north make a resultant of 5 (3-4-5).
        level(
            Chapter.HARBOR,
            """
            ......
            ......
            ....L.
            ......
            ......
            ......
            .S....
            ......
            """,
            v(3, 0), v(0, 4),
        ),
        // 8. The same two cards, but a rock lets only one order through.
        level(
            Chapter.HARBOR,
            """
            #.....
            ......
            ....L.
            ......
            .....#
            ......
            .S.#..
            ......
            """,
            v(3, 0), v(0, 4),
        ),
        // 9. Slanted cards: their components add up separately.
        level(
            Chapter.HARBOR,
            """
            ......
            #.....
            ....L.
            ......
            ......
            ......
            .S..#.
            ......
            """,
            v(2, 1), v(1, 3), v(2, 0),
        ),
        // 10. More cards than needed: find the ones that add up to the way to the harbor.
        level(
            Chapter.HARBOR,
            """
            ......
            ...L..
            ......
            .#....
            ....#.
            ......
            S.....
            ......
            """,
            v(3, 1), v(-1, 2), v(2, 2), v(1, 3), v(0, -2),
        ),

        // ---------------------------------------------------------------- the current
        // 11. The sea carries the boat one square east on every move.
        level(
            Chapter.CURRENT,
            """
            ......
            ......
            ...L..
            ......
            ......
            ......
            .S....
            ......
            """,
            v(0, 2), v(0, 2),
            current = v(1, 0),
        ),
        // 12. Against the current: it pulls south, so aim a little higher.
        level(
            Chapter.CURRENT,
            """
            ......
            ..L...
            ......
            .#....
            ......
            ...#..
            .S....
            ......
            """,
            v(2, 3), v(1, 1), v(-1, 4),
            current = v(0, -1),
        ),
        // 13. A current and a × 2 token together.
        level(
            Chapter.CURRENT,
            """
            ......
            .#..L.
            ......
            ......
            ......
            ....#.
            S.....
            ......
            """,
            v(1, 2), v(0, 1), v(2, 0),
            current = v(1, 0),
            tokens = Tokens(doubles = 1),
        ),

        // ---------------------------------------------------------------- the tugboats
        // 14. A rock on the straight way: split the card into its components and go round it.
        level(
            Chapter.TUGBOATS,
            """
            ......
            ......
            ....L.
            ......
            .#....
            ..#...
            .S....
            ......
            """,
            v(3, 4),
            tokens = Tokens(splits = 1),
        ),
        // 15. Both corners are blocked: two tugboats pull together and sail the diagonal.
        level(
            Chapter.TUGBOATS,
            """
            ......
            ......
            ......
            ....L.
            .#....
            ......
            .S#...
            ......
            """,
            v(3, 0), v(0, 3),
            tokens = Tokens(pairs = 1),
        ),
        // 16. The captain's exam: everything at once.
        level(
            Chapter.TUGBOATS,
            """
            #.....
            ...L..
            ......
            .#..#.
            ......
            ..#...
            S.....
            ......
            """,
            v(4, 2), v(-2, 0), v(1, 3), v(0, 2),
            current = v(0, 1),
            tokens = Tokens(splits = 1, pairs = 1, flips = 1),
        ),
    )
}
