package com.toyquaise.vektor.logic

/**
 * Every level, in order. Maps are drawn top row first, one character per grid point: '.' empty,
 * '#' asteroid, 'S' start, 'P' portal, '*' crystal. Every level gives five units of fuel and two
 * crystals; the tests check that both crystals can be brought to the portal on that fuel. The
 * maps were picked from the generator (GeneratorTest) and tidied by hand.
 */
object Levels {
    private var count = 0
    private fun level(chapter: Chapter, map: String, wind: Vec = Vec.ZERO) = Level.parse(++count, chapter, map, wind)

    val all: List<Level> = listOf(
        // ---------------------------------------------------------------- launch: open space
        // 1. One straight pull: both crystals lie on the way.
        level(
            Chapter.LAUNCH,
            """
            ......
            ......
            ..P...
            ..*...
            ......
            ..*...
            ..S...
            ......
            """,
        ),
        // 2. Slanted: (3, 3) costs √18 ≈ 4,24, less than 3 + 3.
        level(
            Chapter.LAUNCH,
            """
            ......
            ......
            ......
            ....P.
            ...*..
            ..*...
            .S....
            ......
            """,
        ),
        // 3. Past the portal and back: the road (5) is longer than the displacement (3).
        level(
            Chapter.LAUNCH,
            """
            ......
            ..*...
            ..P...
            ......
            ..*...
            ..S...
            ......
            ......
            """,
        ),
        // 4. Crystals off the straight line: a detour, paid in fuel.
        level(
            Chapter.LAUNCH,
            """
            ......
            ......
            ......
            ..*.*.
            .S...P
            ......
            ......
            ......
            """,
        ),
        // 5. A step back first, then the long slanted piece.
        level(
            Chapter.LAUNCH,
            """
            ......
            ......
            ....P.
            ....*.
            ......
            ..*S..
            ......
            ......
            """,
        ),
        // ---------------------------------------------------------------- the asteroid belt
        // 6. A wall with a gap: thread it in small pieces.
        level(
            Chapter.BELT,
            """
            ......
            ......
            ...P..
            ##.###
            ..**..
            ..S...
            ......
            ......
            """,
        ),
        // 7. The slanted way is blocked: along the edges, five units exactly.
        level(
            Chapter.BELT,
            """
            ......
            ......
            ..#.P.
            .###*.
            ..#...
            ..S.*.
            ......
            ......
            """,
        ),
        // 8. Sideways first, then over the asteroid on the slant.
        level(
            Chapter.BELT,
            """
            ......
            .....#
            .P..#.
            ..*#..
            ..#...
            ..S*..
            ......
            ......
            """,
        ),
        // 9. Two walls: through the lower gap on the slant.
        level(
            Chapter.BELT,
            """
            ......
            ......
            ..P*..
            ###*.#
            ......
            #S.###
            ......
            ......
            """,
        ),
        // 10. A slalom round the asteroids.
        level(
            Chapter.BELT,
            """
            ......
            ..#..#
            .....P
            .....#
            #....*
            ....S*
            .....#
            ......
            """,
        ),
        // ---------------------------------------------------------------- the solar wind
        // 11. The wind pushes one square north on every move, for free: six squares on less fuel.
        level(
            Chapter.WIND,
            """
            ..P...
            ......
            ..*...
            ......
            ..*...
            ......
            ..S...
            ......
            """,
            wind = Vec(0, 1),
        ),
        // 12. With the wind, through the gap.
        level(
            Chapter.WIND,
            """
            ....P.
            ......
            ###.##
            ....*.
            ...*..
            ...S..
            ......
            ......
            """,
            wind = Vec(0, 1),
        ),
        // 13. A west wind: aim so that piece plus wind goes where you want.
        level(
            Chapter.WIND,
            """
            ......
            ......
            P...#.
            #.*...
            ...#.#
            ....*S
            ....#.
            ......
            """,
            wind = Vec(-1, 0),
        ),
        // 14. An east wind and a tight tank: five units exactly.
        level(
            Chapter.WIND,
            """
            ......
            .....P
            #.*#.#
            .*....
            ......
            S#...#
            ......
            ......
            """,
            wind = Vec(1, 0),
        ),
        // 15. The pilot's exam: many small pieces ride the wind round the wall.
        level(
            Chapter.WIND,
            """
            ......
            ......
            ...P..
            ......
            .*....
            .#####
            .*....
            S.....
            """,
            wind = Vec(0, 1),
        ),
    )
}
