[versions]
gdx = "1.14.2"
kotlin = "2.4.20"
agp = "9.4.1"
junit = "6.1.3"
admob = "24.4.0"
ump = "3.2.0"

[libraries]
gdx = { module = "com.badlogicgames.gdx:gdx", version.ref = "gdx" }
gdx-freetype = { module = "com.badlogicgames.gdx:gdx-freetype", version.ref = "gdx" }
gdx-backend-lwjgl3 = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl3", version.ref = "gdx" }
gdx-backend-android = { module = "com.badlogicgames.gdx:gdx-backend-android", version.ref = "gdx" }
gdx-platform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "gdx" }
gdx-freetype-platform = { module = "com.badlogicgames.gdx:gdx-freetype-platform", version.ref = "gdx" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
admob = { module = "com.google.android.gms:play-services-ads", version.ref = "admob" }
ump = { module = "com.google.android.ump:user-messaging-platform", version.ref = "ump" }
